accounts:
  - name: eg-authority
    coins: ["200000000fhc", "200000000stake"]
  - name: uk-authority
    coins: ["200000000fhc", "200000000stake"]
  - name: sa-authority
    coins: ["200000000fhc", "200000000stake"]
  - name: au-authority
    coins: ["200000000fhc", "200000000stake"]
  - name: ca-authority
    coins: ["200000000fhc", "200000000stake"]
  - name: fr-authority
    coins: ["200000000fhc", "200000000stake"]
  - name: ge-authority
    coins: ["200000000fhc", "200000000stake"]
  - name: ru-authority
    coins: ["200000000fhc", "200000000stake"]
  - name: bf-authority
    coins: ["200000000fhc", "200000000stake"]
  - name: br-authority
    coins: ["200000000fhc", "200000000stake"]

validator:
  name: "eg-authority"
  staked: "10000000stake"

genesis:
  chain_id: "authority"
  
faucet:
  host: ":4500"
  name: eg-authority
  coins: ["1000fhc", "100000stake"]
  
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"


init:
  home: "$HOME/.authority"
  
host:
  rpc: ":26650"
  p2p: ":26651"
  prof: ":6050"
  grpc: ":9050"
  grpc-web: ":9051"
  api: ":1310"
